// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

using thewhiskeystudy.lib.DAL;

namespace thewhiskeystudy.Migrations
{
    [DbContext(typeof(DBFactory))]
    partial class DBFactoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("thewhiskeystudy.DAL.Tables.Reviews", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Body");

                    b.Property<int>("Category");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("ObtainabilityStatus");

                    b.Property<double>("OverallScore");

                    b.Property<double>("Price");

                    b.Property<string>("Title");

                    b.Property<string>("URL");

                    b.Property<int>("YearReleased");

                    b.HasKey("ID");

                    b.ToTable("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
